version: "3.8"

services:
  app:
    container_name: deepanshu_garg_assignment11
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/deepanshu_garg_site/src
    ports:
      - 7775:3000